### ISSUE TITLE
Gifs are huge

### ISSUE THREAD

**Issue by albinso** [albinso/TaleMaps#2]
Based on the most recent discussion in https://github.com/python-pillow/Pillow/issues/617 it seems as if Pillow doesn't actually do any form of gif compression which would explain why our gifs are so massive. The maps should be very efficient to compress since the changes from frame to frame are so miniscule.

**Comment by cervyvin** [comment]
A suggestion might be to use a more compressed format, like mp4 instead.

**Comment by albinso** [comment]
Resolved by 70d3b5d87238a3e7ffbf519cfba10b21bce8bf8d
